version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    container_name: 'flask-6'
    volumes:
      - .:/application
    ports:
      - "4459:4459"
    networks:
      - app


networks:
  app:
    driver: bridge