# Generated by Django 3.0.6 on 2021-12-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0007_auto_20210814_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status_public',
            field=models.BooleanField(default=True),
        ),
    ]
