version: "3"
#

services:
  app:
    build:
      context: ./
      dockerfile: docker/python/Dockerfile
    container_name: 'flask-intro'
    volumes:
      - .:/flask
    ports:
      - "8080:8080"
    networks:
      - app


networks:
  app:
    driver: bridge
