# Generated by Django 3.0.6 on 2021-12-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='some@some', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.TextField(default='some message'),
            preserve_default=False,
        ),
    ]
