# Generated by Django 3.0.6 on 2021-12-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
