version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    container_name: 'flask-weather-hw'

    volumes:
      - .:/application
    ports:
      - "4456:4456"

