version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: docker/python/Dockerfile
    container_name: 'flask-renee'

    volumes:
      - .:/application
    ports:
      - '9000:9000'
    networks:
      - app


networks:
  app:
    driver: bridge